// Fetches top-10 EOA holders of the given tokens from Robinhood Chain Blockscout
// and prints a src/data/expansion.ts module. Re-run to refresh the wallet list.
//   node scripts/fetch-holders.mjs SYMBOL1 SYMBOL2 ...
const BASE = process.env.EXPLORER_BASE || 'https://robinhoodchain.blockscout.com';
const ZERO = '0x0000000000000000000000000000000000000000';
const DEAD = '0x000000000000000000000000000000000000dead';

const get = async (u) => {
  const r = await fetch(u, { headers: { 'user-agent': 'swarm-the-fly' } });
  if (!r.ok) throw new Error(`${u} -> ${r.status}`);
  return r.json();
};

const symbols = process.argv.slice(2).map((s) => s.toUpperCase());

const list = await get(`${BASE}/api/v2/tokens?type=ERC-20`);
const bySym = new Map();
for (const t of list.items ?? []) bySym.set((t.symbol || '').toUpperCase(), t);

const tokens = [];
const holders = {};
for (const sym of symbols) {
  const t = bySym.get(sym);
  if (!t) { console.error(`! ${sym} not found in tokens list`); continue; }
  const addr = t.address_hash;
  const supply = Number(t.total_supply || 0);
  const h = await get(`${BASE}/api/v2/tokens/${addr}/holders`);
  const rows = [];
  for (const item of h.items ?? []) {
    const a = item.address ?? {};
    const hash = (a.hash || '').toLowerCase();
    if (a.is_contract) continue;                 // exclude LP pools, routers, adapters
    if (hash === ZERO || hash === DEAD) continue; // exclude burn/zero
    const pct = supply > 0 ? (Number(item.value) / supply) * 100 : 0;
    rows.push({ address: a.hash, pct: Number(pct.toFixed(2)) });
    if (rows.length >= 10) break;
  }
  tokens.push({ symbol: sym, name: t.name || sym, address: addr, totalSupply: supply / 10 ** Number(t.decimals || 18) });
  holders[sym] = rows;
  console.error(`✓ ${sym}: ${rows.length} EOA holders`);
}

const out =
`// AUTO-GENERATED by scripts/fetch-holders.mjs — top-10 EOA holders of additional
// Robinhood Chain tokens (LP pools / contracts / burn addresses excluded).
// Re-run the script to refresh. Do not edit by hand.
import type { RawTokenSeed, RawHolderSeed } from './seed.js';

export const EXPANSION_TOKENS: RawTokenSeed[] = ${JSON.stringify(tokens, null, 2)};

export const EXPANSION_HOLDERS: Record<string, RawHolderSeed[]> = ${JSON.stringify(holders, null, 2)};
`;
process.stdout.write(out);
