// Fetches top-N EOA holders of the given tokens from Robinhood Chain Blockscout
// and prints the src/data/holders.generated.ts module. Re-run to refresh.
//   node scripts/fetch-holders.mjs SYMBOL | SYMBOL=0xADDRESS | SYMBOL@N | SYMBOL=0xADDRESS@N
//     =0xADDRESS  → for tokens not on the explorer's first tokens page
//     @N          → keep only the top N holders (default 10)
const BASE = process.env.EXPLORER_BASE || 'https://robinhoodchain.blockscout.com';
const ZERO = '0x0000000000000000000000000000000000000000';
const DEAD = '0x000000000000000000000000000000000000dead';

const get = async (u) => {
  const r = await fetch(u, { headers: { 'user-agent': 'swarm-the-fly' } });
  if (!r.ok) throw new Error(`${u} -> ${r.status}`);
  return r.json();
};

const args = process.argv.slice(2).map((s) => {
  const [main, limStr] = s.split('@');
  const [sym, addr] = main.split('=');
  return { sym: sym.toUpperCase(), addr, limit: limStr ? Number(limStr) : 10 };
});

const list = await get(`${BASE}/api/v2/tokens?type=ERC-20`);
const bySym = new Map();
for (const t of list.items ?? []) bySym.set((t.symbol || '').toUpperCase(), t);

const tokens = [];
const holders = {};
for (const { sym, addr: overrideAddr, limit } of args) {
  let t = bySym.get(sym);
  const addr = overrideAddr ?? t?.address_hash;
  if (!addr) { console.error(`! ${sym} not found (pass ${sym}=0xADDRESS)`); continue; }
  if (!t) t = await get(`${BASE}/api/v2/tokens/${addr}`); // metadata by address
  const supply = Number(t.total_supply || 0);
  const h = await get(`${BASE}/api/v2/tokens/${addr}/holders`);
  const rows = [];
  for (const item of h.items ?? []) {
    const a = item.address ?? {};
    const hash = (a.hash || '').toLowerCase();
    if (a.is_contract) continue;                 // exclude LP pools, routers, adapters
    if (hash === ZERO || hash === DEAD) continue; // exclude burn/zero
    const pct = supply > 0 ? (Number(item.value) / supply) * 100 : 0;
    rows.push({ address: a.hash, pct: Number(pct.toFixed(2)) });
    if (rows.length >= limit) break;
  }
  tokens.push({ symbol: sym, name: t.name || sym, address: addr, totalSupply: supply / 10 ** Number(t.decimals || 18) });
  holders[sym] = rows;
  console.error(`✓ ${sym}: ${rows.length} EOA holders`);
}

const out =
`// AUTO-GENERATED by scripts/fetch-holders.mjs — top-N EOA holders per token on
// Robinhood Chain (LP pools / contracts / burn addresses excluded via the
// explorer's is_contract flag). Re-run the script to refresh. Do not edit by hand.
import type { RawTokenSeed, RawHolderSeed } from './seed.js';

export const TRACKED_TOKENS_RAW: RawTokenSeed[] = ${JSON.stringify(tokens, null, 2)};

export const TRACKED_HOLDERS_RAW: Record<string, RawHolderSeed[]> = ${JSON.stringify(holders, null, 2)};
`;
process.stdout.write(out);
