// AUTO-GENERATED by scripts/fetch-holders.mjs — top-10 EOA holders of additional
// Robinhood Chain tokens (LP pools / contracts / burn addresses excluded).
// Re-run the script to refresh. Do not edit by hand.
import type { RawTokenSeed, RawHolderSeed } from './seed.js';

export const EXPANSION_TOKENS: RawTokenSeed[] = [
  {
    "symbol": "WOOD",
    "name": "Sherwood Protocol",
    "address": "0xF8BC08092C06dB6148114DCf82AF881F1085f92b",
    "totalSupply": 1000000000
  },
  {
    "symbol": "HOODRAT",
    "name": "Hoodrat",
    "address": "0x8e62F281f282686fCa6dCB39288069a93fC23F1c",
    "totalSupply": 1000000000
  },
  {
    "symbol": "ARROW",
    "name": "Arrow",
    "address": "0xf2915d1e3C1B0c769d0c756Ec43F1c1f6c99cD03",
    "totalSupply": 10000000
  },
  {
    "symbol": "YOLO",
    "name": "YOLO",
    "address": "0x62C71cd34a52c30d894419CBcc55Db2aFA8032eA",
    "totalSupply": 1000000000
  },
  {
    "symbol": "RAXOL",
    "name": "RAXOL",
    "address": "0xf44702b17d9abD53815F703e772F35E9c71A53af",
    "totalSupply": 1000000000
  },
  {
    "symbol": "KARMA",
    "name": "Karma by Virtuals",
    "address": "0xB47f4702DEB124cb4eB6286bE83c9d84277C6239",
    "totalSupply": 1000000000
  },
  {
    "symbol": "HMM",
    "name": "Thinking Cat",
    "address": "0x7FE995a80075dF3Dc8Ae11A9b82c7FE4202CD87f",
    "totalSupply": 1000000000
  }
];

export const EXPANSION_HOLDERS: Record<string, RawHolderSeed[]> = {
  "WOOD": [
    {
      "address": "0xF577EA2790639F86E3d0500998eFc1dEb8FAC0d6",
      "pct": 0.5
    },
    {
      "address": "0x2B1F1dC565Be679F8673D13676e0250755cc3A8d",
      "pct": 0.44
    },
    {
      "address": "0xe904E5e7Af49033057F3b30e265d5e6771D01651",
      "pct": 0.43
    },
    {
      "address": "0xE739EFE689Dc9EC63187559e89EfC5Db89883C6B",
      "pct": 0.43
    },
    {
      "address": "0x1d756248Ae6c3C6abF65BAd4c80A4D7Ed3B0f75D",
      "pct": 0.43
    },
    {
      "address": "0x3155D8ca6938f5823e1Da599208abfdCB6392379",
      "pct": 0.43
    },
    {
      "address": "0x4d27c4728463925A3c58f8190753d683e189f04B",
      "pct": 0.43
    },
    {
      "address": "0x249666ee8591D96bE723199781FA5694eC209ea6",
      "pct": 0.41
    },
    {
      "address": "0x7fb7D71c92F9DBB35210c5602f47FCd32ef87653",
      "pct": 0.41
    },
    {
      "address": "0x72f82AAB1D2BD61F3Dd021F94aD62C533ea0256E",
      "pct": 0.41
    }
  ],
  "HOODRAT": [
    {
      "address": "0xD71ebB8e50DaB8d3aeB82A76D47C88c489333A27",
      "pct": 3
    },
    {
      "address": "0x35D42CaCAA7F8958Ab2427BFBfb29D73cf24DAd6",
      "pct": 2.19
    },
    {
      "address": "0x2dBAf98620aC5Bbe3441f756fEfF82702D095b1a",
      "pct": 2.06
    },
    {
      "address": "0x61C0293D364C7F1927993689F95fD14334e7f7E2",
      "pct": 1.46
    },
    {
      "address": "0xD7FeB56aE410681B16443B3586000A28A77BA853",
      "pct": 1.18
    },
    {
      "address": "0xe75B826894184413503A26AF18B8feE6270cF3D3",
      "pct": 1.03
    },
    {
      "address": "0x9963597a9246b39b13330992F571F8378c18c262",
      "pct": 1
    },
    {
      "address": "0xf4F47448f3b9C2273Ce6ABd8c5Be563e8B5f5F19",
      "pct": 1
    },
    {
      "address": "0x1fB9A19Fcd8819854E5C654c713229EdA05af137",
      "pct": 1
    },
    {
      "address": "0x56E95b47A07210f1eA9fA418C7c5DC164C419Ac0",
      "pct": 0.9
    }
  ],
  "ARROW": [
    {
      "address": "0xC1c2Ed875691625fE6aF6f210036FB4cB3cd1e73",
      "pct": 0.78
    },
    {
      "address": "0x2dBAf98620aC5Bbe3441f756fEfF82702D095b1a",
      "pct": 0.73
    },
    {
      "address": "0xF20Ca25E0Af99f276d77A078E8879Bb3bEebbe57",
      "pct": 0.55
    },
    {
      "address": "0x9963597a9246b39b13330992F571F8378c18c262",
      "pct": 0.5
    },
    {
      "address": "0xeac1fDd00ab2CA69f97d17e87510776b5546c4c3",
      "pct": 0.5
    },
    {
      "address": "0xD1B13C91BBE6322D0C7Dbc36334D184728Addb88",
      "pct": 0.5
    },
    {
      "address": "0x9b0f550638Ba7e03F50BEbB303b138DA676191d7",
      "pct": 0.5
    },
    {
      "address": "0x83dEEF2b8da958F1C6c95a9d936CB881247C1060",
      "pct": 0.5
    },
    {
      "address": "0x791f8578FfFC693166EdDd54dfbBd918CD65297f",
      "pct": 0.5
    },
    {
      "address": "0x3212f145Ca0F031544CA9b6a0086174F057A3bFb",
      "pct": 0.5
    }
  ],
  "YOLO": [
    {
      "address": "0xE0b5Ee397C1684565e581c1566370C39d6393e55",
      "pct": 4.58
    },
    {
      "address": "0xFEFD188448947C97e52774cd30D1cECe5F201F17",
      "pct": 3.33
    },
    {
      "address": "0x36305A9c9EBb7bD8C9bd53cFd1fd510228060D92",
      "pct": 1.89
    },
    {
      "address": "0x789883e233645ae4114E72155fb58b7549a34A24",
      "pct": 1.88
    },
    {
      "address": "0x74b23Ecb1692363F0532069801Ce47D027417FB1",
      "pct": 1.23
    },
    {
      "address": "0x2AA9da61Eff59037eB661e2784Eb405673C19263",
      "pct": 1.22
    },
    {
      "address": "0x0a6EBEd0155EDB4b21D92AD02897A626CD90119E",
      "pct": 1.19
    },
    {
      "address": "0x6d259869Be6f63AD5EB8a27C53A97532Af803F38",
      "pct": 1.16
    },
    {
      "address": "0x492CE2CE9734CdC3488A0086b81212b3aaC40947",
      "pct": 1.14
    },
    {
      "address": "0xBd716393f9CEf81213CC49deCdDA1946C100c51d",
      "pct": 1.11
    }
  ],
  "RAXOL": [
    {
      "address": "0xe2890629EF31b32132003C02B29a50A025dEeE8a",
      "pct": 18.95
    },
    {
      "address": "0x829d1853D4ED1f80D6c223AE8828DBDBbC1E224a",
      "pct": 4.47
    },
    {
      "address": "0x5638484ba2d2F1D1D35020572B0Aa439a9869192",
      "pct": 1.07
    },
    {
      "address": "0x6fCe541eE57550CaDFA6a6E9b3450Ae35BC9179c",
      "pct": 0.74
    },
    {
      "address": "0xed5f5e5F9D3B6DC69A4C5088D80AE358Bb4f6134",
      "pct": 0.74
    },
    {
      "address": "0x55328Ff701aE1c3B9E100C2eBF82A61aB9AD5995",
      "pct": 0.71
    },
    {
      "address": "0x82608Cb7bA84322a7a0d4cC0Df8F1D2D065877ef",
      "pct": 0.68
    },
    {
      "address": "0xC0e7EA1a1ced9007f5fB45CD45908746A87Ee79B",
      "pct": 0.65
    },
    {
      "address": "0xf5948dc2b78b826EE196E54CB1b7c64cB1ca30CC",
      "pct": 0.59
    },
    {
      "address": "0x4e03cfb39c0e9aD3E8608A9749cd07FCc3E5F6F0",
      "pct": 0.55
    }
  ],
  "KARMA": [
    {
      "address": "0xe2890629EF31b32132003C02B29a50A025dEeE8a",
      "pct": 18.95
    },
    {
      "address": "0x07Cd9A8597Fc4D00a3690992A1b7151131F76758",
      "pct": 9.78
    },
    {
      "address": "0x829d1853D4ED1f80D6c223AE8828DBDBbC1E224a",
      "pct": 1.56
    },
    {
      "address": "0xa9090D67e8F9daE35A90921E08f88CD74036694c",
      "pct": 0.72
    },
    {
      "address": "0x49B6b1Fc759C1b0B4397d9Ab9fbCab0442B5F460",
      "pct": 0.7
    },
    {
      "address": "0x2C9Ee560e9D05E5df0764B9C9451b71498dE43c0",
      "pct": 0.59
    },
    {
      "address": "0xD72e00E6B984Ced3234f8B0ede7d33B04b8D63C1",
      "pct": 0.58
    },
    {
      "address": "0x578A629dF669BE6e873f142903373BA29F7e2b1F",
      "pct": 0.46
    },
    {
      "address": "0x4b4A17fBD2fD65c5Ace3e533080147DB343a893E",
      "pct": 0.41
    },
    {
      "address": "0x24E414606a7BeC29a56C3cbD3Eae5665DD0477A7",
      "pct": 0.39
    }
  ],
  "HMM": [
    {
      "address": "0x6434d19C2E6788E53AA3ec5c6fc0112b1852E554",
      "pct": 2.42
    },
    {
      "address": "0x3E93C7BBAc9CB8A0DfadbbE76B092A456652af6a",
      "pct": 1.85
    },
    {
      "address": "0xa48492aDb2eE4Fca90E2ca52af78a834A4D6b656",
      "pct": 1.85
    },
    {
      "address": "0xda4bCee76B29EFEc9697Fcf663601c2042043968",
      "pct": 1.58
    },
    {
      "address": "0x7Fac2160bAb6D465107A10A1B13f6e7EBe8B4A2c",
      "pct": 1.41
    },
    {
      "address": "0x00077705952C90b728c6D7dc450bEb4429331111",
      "pct": 1.29
    },
    {
      "address": "0xdA5f2Acaa975a65dCf8166E1F1bB8b36264733b9",
      "pct": 1.11
    },
    {
      "address": "0xb990465Dc0293082FABC4aFB03c35539503b4eab",
      "pct": 1.1
    },
    {
      "address": "0x750d25bDDD713ead00cb6953A9F0eb4489F5D56e",
      "pct": 1.04
    },
    {
      "address": "0x16354Ec44309c0EBd0530883Cb96674Ff267695d",
      "pct": 1.01
    }
  ]
};
