// AUTO-GENERATED by scripts/fetch-holders.mjs — top-N EOA holders per token on
// Robinhood Chain (LP pools / contracts / burn addresses excluded via the
// explorer's is_contract flag). Re-run the script to refresh. Do not edit by hand.
import type { RawTokenSeed, RawHolderSeed } from './seed.js';

export const TRACKED_TOKENS_RAW: RawTokenSeed[] = [
  {
    "symbol": "CASHCAT",
    "name": "Cash Cat",
    "address": "0x020bfC650A365f8BB26819deAAbF3E21291018b4",
    "totalSupply": 1000000000
  },
  {
    "symbol": "TENDIES",
    "name": "TENDIES",
    "address": "0x45242320DBB855EeA8Fd36804C6487E10E97FCF9",
    "totalSupply": 1000000000
  },
  {
    "symbol": "PONS",
    "name": "Pons",
    "address": "0x39dBED3a2bd333467115dE45665cC57F813C4571",
    "totalSupply": 1000000000
  },
  {
    "symbol": "INDEX",
    "name": "The Index",
    "address": "0x56910D4409F3a0C78C64DD8D0545FF0705389870",
    "totalSupply": 1000000000
  },
  {
    "symbol": "STONKBROKER",
    "name": "StonkBroker",
    "address": "0xe934e36A439C94017B64a3FecE66AF12099aBF50",
    "totalSupply": 2695364457
  },
  {
    "symbol": "VEX",
    "name": "ProjectVex",
    "address": "0x8Ff92566f2e81BDd68EDfAa8cde73942A723796b",
    "totalSupply": 1000000000
  },
  {
    "symbol": "JUGGERNAUT",
    "name": "The Juggernaut",
    "address": "0xD7321801CAae694090694Ff55A9323139F043B88",
    "totalSupply": 1000000000
  },
  {
    "symbol": "WISHBONE",
    "name": "WISHBONE",
    "address": "0x77581054581B9c525E7dd7a0155DE43867532d03",
    "totalSupply": 1000000000
  },
  {
    "symbol": "WOOD",
    "name": "Sherwood Protocol",
    "address": "0xF8BC08092C06dB6148114DCf82AF881F1085f92b",
    "totalSupply": 1000000000
  },
  {
    "symbol": "HOODRAT",
    "name": "Hoodrat",
    "address": "0x8e62F281f282686fCa6dCB39288069a93fC23F1c",
    "totalSupply": 1000000000
  },
  {
    "symbol": "ARROW",
    "name": "Arrow",
    "address": "0xf2915d1e3C1B0c769d0c756Ec43F1c1f6c99cD03",
    "totalSupply": 10000000
  },
  {
    "symbol": "YOLO",
    "name": "YOLO",
    "address": "0x62C71cd34a52c30d894419CBcc55Db2aFA8032eA",
    "totalSupply": 1000000000
  },
  {
    "symbol": "RAXOL",
    "name": "RAXOL",
    "address": "0xf44702b17d9abD53815F703e772F35E9c71A53af",
    "totalSupply": 1000000000
  },
  {
    "symbol": "KARMA",
    "name": "Karma by Virtuals",
    "address": "0xB47f4702DEB124cb4eB6286bE83c9d84277C6239",
    "totalSupply": 1000000000
  },
  {
    "symbol": "HMM",
    "name": "Thinking Cat",
    "address": "0x7FE995a80075dF3Dc8Ae11A9b82c7FE4202CD87f",
    "totalSupply": 1000000000
  }
];

export const TRACKED_HOLDERS_RAW: Record<string, RawHolderSeed[]> = {
  "CASHCAT": [
    {
      "address": "0x2dBAf98620aC5Bbe3441f756fEfF82702D095b1a",
      "pct": 2.8
    },
    {
      "address": "0xeb877e7b5614B1Ca58c6b00eC4FFCd248eD414ee",
      "pct": 1.7
    },
    {
      "address": "0x7c85a758c75b4dFCd00A1730863A7520F90AA08D",
      "pct": 1.34
    },
    {
      "address": "0x9963597a9246b39b13330992F571F8378c18c262",
      "pct": 1.15
    },
    {
      "address": "0x3EA937589eA5eE0FBcCbcCeF29473E7f957a19a5",
      "pct": 1.02
    },
    {
      "address": "0x03e8FB0f68D497936231A1DE70F84bC33B568529",
      "pct": 1.01
    },
    {
      "address": "0x5638484ba2d2F1D1D35020572B0Aa439a9869192",
      "pct": 0.99
    },
    {
      "address": "0x77acC36fCC41DC3BFB51441E003831c74D4ecAF0",
      "pct": 0.79
    },
    {
      "address": "0xaAe01D26A2100224F724dF95fAFACD1d07C13593",
      "pct": 0.72
    },
    {
      "address": "0xF0C9977eE6278E5544168C76A5eD25b8Bf9F3936",
      "pct": 0.71
    }
  ],
  "TENDIES": [
    {
      "address": "0xD1BF5f917EA367b37cb4Eec6D41D8433a12fC8fD",
      "pct": 1.41
    },
    {
      "address": "0x9963597a9246b39b13330992F571F8378c18c262",
      "pct": 1.41
    },
    {
      "address": "0x71f2F1c2dc94cDaBFE29Cb355119f8683AE0969b",
      "pct": 1.21
    },
    {
      "address": "0xe7D96B5FdaB3DCb6AB5Cb8B14b291E03A8AC496b",
      "pct": 1.01
    },
    {
      "address": "0xC52FBB9C4a7373b85De6415f888e5E2e3F195176",
      "pct": 1
    },
    {
      "address": "0xFD6e86cf9AECA787CFFB198BCA859d459a44a847",
      "pct": 1
    },
    {
      "address": "0x11C8678069c46B74C62A8a94B21784DFb771b8d3",
      "pct": 1
    },
    {
      "address": "0xF0C9977eE6278E5544168C76A5eD25b8Bf9F3936",
      "pct": 0.99
    },
    {
      "address": "0x7DD4C4EBa4DA65ED85A5e56Fa7cA1068b3aB920a",
      "pct": 0.99
    },
    {
      "address": "0xB953EE0e28c0557642f404BBB4F68A89593F875a",
      "pct": 0.9
    }
  ],
  "PONS": [
    {
      "address": "0x194d98d18113bDD5720A0a89FE2F98C75ECe7344",
      "pct": 1.27
    },
    {
      "address": "0x0a6EBEd0155EDB4b21D92AD02897A626CD90119E",
      "pct": 1.1
    },
    {
      "address": "0x7e3Ba68C49561AaE7c23C1d20fEF0F1D7615a3ad",
      "pct": 1.02
    },
    {
      "address": "0x61C0293D364C7F1927993689F95fD14334e7f7E2",
      "pct": 1.02
    },
    {
      "address": "0x9963597a9246b39b13330992F571F8378c18c262",
      "pct": 0.91
    },
    {
      "address": "0x38053BB358106b2d212c3130dcd28Df19f2D2EFF",
      "pct": 0.9
    },
    {
      "address": "0x6B16a08c3962eC11C90faB1669330f9BE54532a8",
      "pct": 0.9
    },
    {
      "address": "0x0eF27ea387dB2791C5C50CEA43bE5b5503701803",
      "pct": 0.75
    },
    {
      "address": "0x0cC7CEdb0935ceaB0B4A6B38eE7dcfd403b19A7b",
      "pct": 0.72
    },
    {
      "address": "0x975D368a9a2BC2028Eec2b08E8F6456389288ABa",
      "pct": 0.7
    }
  ],
  "INDEX": [
    {
      "address": "0xB646Fa75E09b37327505106e39D84b89c4E68413",
      "pct": 2.01
    },
    {
      "address": "0x14e468E79D14606035A86A6B068A93BeaDa853f8",
      "pct": 1.87
    },
    {
      "address": "0x7Da8b5A80539A0F960C91ae0830A22a807Edd739",
      "pct": 1.32
    },
    {
      "address": "0xC26912365421474C271e9a7C6c534419Dc9D7a38",
      "pct": 1.27
    },
    {
      "address": "0xbb3b32E63F6B2D2605A5114416398fA3839328b8",
      "pct": 1.2
    },
    {
      "address": "0x491f8C0bB7b970A554A82721B19aa5b9E0a90455",
      "pct": 1.13
    },
    {
      "address": "0x6Fd2e7Fa124b7d9D021935D1f99ded0D92DfFaA8",
      "pct": 0.99
    },
    {
      "address": "0x44dF085447dBEBCf69C6675c3B8A795c7fdeB3F4",
      "pct": 0.99
    },
    {
      "address": "0x4671fb2fB50a8001E13523a8a3dF37Bc67777777",
      "pct": 0.93
    },
    {
      "address": "0x9963597a9246b39b13330992F571F8378c18c262",
      "pct": 0.92
    }
  ],
  "STONKBROKER": [
    {
      "address": "0x9963597a9246b39b13330992F571F8378c18c262",
      "pct": 1.06
    },
    {
      "address": "0x59F90189365B96A6DbE355Ed91363551160E4A7C",
      "pct": 1
    },
    {
      "address": "0x5678C23be6989Cde5D0fE68D921584B4404a3180",
      "pct": 0.89
    },
    {
      "address": "0x8FABe392DF90b06ad610C33F41bB1Abd78A5Fc20",
      "pct": 0.74
    },
    {
      "address": "0x2DaA0456786A065ee17D1eDaCC231F9Acd6f018b",
      "pct": 0.73
    },
    {
      "address": "0x368cbFdf48031c07deFf5D4e05e270db29ffC085",
      "pct": 0.67
    },
    {
      "address": "0x148Ff8c581be8A7F3536F28bDFD7C84dd109ba91",
      "pct": 0.6
    },
    {
      "address": "0xbd2895Dc008c31ba7b2E9177EbEC4E7B048ACB86",
      "pct": 0.58
    },
    {
      "address": "0x96B13D47C17d61DC42F2152FA39Cf3acffc7eBfC",
      "pct": 0.51
    },
    {
      "address": "0x45A3b27B13c6a4fE90a1a7E8CdcB24D80Abc71CD",
      "pct": 0.5
    }
  ],
  "VEX": [
    {
      "address": "0xe2890629EF31b32132003C02B29a50A025dEeE8a",
      "pct": 14.05
    },
    {
      "address": "0x829d1853D4ED1f80D6c223AE8828DBDBbC1E224a",
      "pct": 4.49
    },
    {
      "address": "0xBAa11e7357525aE586826482B12bc07D70C25920",
      "pct": 2
    },
    {
      "address": "0x740d62Ca581672A38cFf476b1c1578B061523FF8",
      "pct": 1.93
    },
    {
      "address": "0x32e7c4AFEA4f868A53EC51435C92eD80625EeB33",
      "pct": 1.56
    },
    {
      "address": "0xdCc200ceE7a6453FBC5E26D6c7C91708F80FCFd5",
      "pct": 1.05
    },
    {
      "address": "0x585aD02E878364a22099da8B8217E586b79711d2",
      "pct": 0.9
    },
    {
      "address": "0xBAf7C36C047cdA4430aae60a7F2949192721B80A",
      "pct": 0.84
    },
    {
      "address": "0x49B6b1Fc759C1b0B4397d9Ab9fbCab0442B5F460",
      "pct": 0.75
    },
    {
      "address": "0x39eac10DFC7e03E57FFFd048FC2E1A3668f4b93b",
      "pct": 0.71
    }
  ],
  "JUGGERNAUT": [
    {
      "address": "0x71f2F1c2dc94cDaBFE29Cb355119f8683AE0969b",
      "pct": 2.75
    },
    {
      "address": "0x8E65cbcDc822968131B1e37E5CEE02c9CE82Ab21",
      "pct": 2.05
    },
    {
      "address": "0x56d317B87344538De94371a1593613a4bD6FA7A4",
      "pct": 1.28
    },
    {
      "address": "0x4F835C3bbE19b569FBFceaBc42C95631F354B532",
      "pct": 1.1
    },
    {
      "address": "0x5638484ba2d2F1D1D35020572B0Aa439a9869192",
      "pct": 1.08
    },
    {
      "address": "0x491f8C0bB7b970A554A82721B19aa5b9E0a90455",
      "pct": 1.02
    },
    {
      "address": "0x9963597a9246b39b13330992F571F8378c18c262",
      "pct": 1
    },
    {
      "address": "0x9Cb9B0e30e4Cee504216a1ecA32e64F64ecb1509",
      "pct": 0.96
    },
    {
      "address": "0xb5AEC0e9eEA1B91575aF115d29369b2376de2674",
      "pct": 0.95
    },
    {
      "address": "0xAC6da909F2132e680aa4998263dA00f519C1946b",
      "pct": 0.94
    }
  ],
  "WISHBONE": [
    {
      "address": "0x0F0732ffD97CEdF619bd969ec93b25F8Fc1231DC",
      "pct": 2.53
    },
    {
      "address": "0xAAfA64632E0873BfAb19f051E0C4b768C992638c",
      "pct": 1.41
    },
    {
      "address": "0x2f25b929f03Fe2869e752f1910e5445f8B5778dA",
      "pct": 1.37
    },
    {
      "address": "0xB89C70e8EfA86e184591744b11587c7EF7cB5e60",
      "pct": 1.37
    },
    {
      "address": "0x2dBAf98620aC5Bbe3441f756fEfF82702D095b1a",
      "pct": 1.26
    },
    {
      "address": "0x98c43dA65205b7c53A857d79f3D1F6fBC0b76fA5",
      "pct": 1.24
    },
    {
      "address": "0x2B23525618d38AfF20EFbf00bF3D12d023B1C910",
      "pct": 1.23
    },
    {
      "address": "0x0e0cb46e1ddfcCeD88AB552871d88dF52D61AD9E",
      "pct": 1.18
    },
    {
      "address": "0x60118B5e13C3DB8B1E5d446C410f12F343d7d1db",
      "pct": 1.1
    },
    {
      "address": "0x71f2F1c2dc94cDaBFE29Cb355119f8683AE0969b",
      "pct": 1.07
    }
  ],
  "WOOD": [
    {
      "address": "0xF577EA2790639F86E3d0500998eFc1dEb8FAC0d6",
      "pct": 0.5
    },
    {
      "address": "0x2B1F1dC565Be679F8673D13676e0250755cc3A8d",
      "pct": 0.44
    },
    {
      "address": "0xe904E5e7Af49033057F3b30e265d5e6771D01651",
      "pct": 0.43
    },
    {
      "address": "0xE739EFE689Dc9EC63187559e89EfC5Db89883C6B",
      "pct": 0.43
    },
    {
      "address": "0x1d756248Ae6c3C6abF65BAd4c80A4D7Ed3B0f75D",
      "pct": 0.43
    },
    {
      "address": "0x3155D8ca6938f5823e1Da599208abfdCB6392379",
      "pct": 0.43
    },
    {
      "address": "0x4d27c4728463925A3c58f8190753d683e189f04B",
      "pct": 0.43
    },
    {
      "address": "0x249666ee8591D96bE723199781FA5694eC209ea6",
      "pct": 0.41
    },
    {
      "address": "0x7fb7D71c92F9DBB35210c5602f47FCd32ef87653",
      "pct": 0.41
    },
    {
      "address": "0x72f82AAB1D2BD61F3Dd021F94aD62C533ea0256E",
      "pct": 0.41
    }
  ],
  "HOODRAT": [
    {
      "address": "0xD71ebB8e50DaB8d3aeB82A76D47C88c489333A27",
      "pct": 3
    },
    {
      "address": "0x35D42CaCAA7F8958Ab2427BFBfb29D73cf24DAd6",
      "pct": 2.19
    },
    {
      "address": "0x2dBAf98620aC5Bbe3441f756fEfF82702D095b1a",
      "pct": 2.11
    },
    {
      "address": "0x61C0293D364C7F1927993689F95fD14334e7f7E2",
      "pct": 1.46
    },
    {
      "address": "0xD7FeB56aE410681B16443B3586000A28A77BA853",
      "pct": 1.18
    },
    {
      "address": "0xe75B826894184413503A26AF18B8feE6270cF3D3",
      "pct": 1.03
    },
    {
      "address": "0x9963597a9246b39b13330992F571F8378c18c262",
      "pct": 1
    },
    {
      "address": "0xf4F47448f3b9C2273Ce6ABd8c5Be563e8B5f5F19",
      "pct": 1
    },
    {
      "address": "0x1fB9A19Fcd8819854E5C654c713229EdA05af137",
      "pct": 1
    },
    {
      "address": "0x56E95b47A07210f1eA9fA418C7c5DC164C419Ac0",
      "pct": 0.9
    }
  ],
  "ARROW": [
    {
      "address": "0xC1c2Ed875691625fE6aF6f210036FB4cB3cd1e73",
      "pct": 0.78
    },
    {
      "address": "0x2dBAf98620aC5Bbe3441f756fEfF82702D095b1a",
      "pct": 0.72
    },
    {
      "address": "0xF20Ca25E0Af99f276d77A078E8879Bb3bEebbe57",
      "pct": 0.55
    },
    {
      "address": "0x9963597a9246b39b13330992F571F8378c18c262",
      "pct": 0.5
    },
    {
      "address": "0xeac1fDd00ab2CA69f97d17e87510776b5546c4c3",
      "pct": 0.5
    },
    {
      "address": "0xD1B13C91BBE6322D0C7Dbc36334D184728Addb88",
      "pct": 0.5
    },
    {
      "address": "0x9b0f550638Ba7e03F50BEbB303b138DA676191d7",
      "pct": 0.5
    },
    {
      "address": "0x83dEEF2b8da958F1C6c95a9d936CB881247C1060",
      "pct": 0.5
    },
    {
      "address": "0x791f8578FfFC693166EdDd54dfbBd918CD65297f",
      "pct": 0.5
    },
    {
      "address": "0x3212f145Ca0F031544CA9b6a0086174F057A3bFb",
      "pct": 0.5
    }
  ],
  "YOLO": [
    {
      "address": "0xE0b5Ee397C1684565e581c1566370C39d6393e55",
      "pct": 4.58
    },
    {
      "address": "0xFEFD188448947C97e52774cd30D1cECe5F201F17",
      "pct": 3.33
    },
    {
      "address": "0x36305A9c9EBb7bD8C9bd53cFd1fd510228060D92",
      "pct": 1.89
    },
    {
      "address": "0x789883e233645ae4114E72155fb58b7549a34A24",
      "pct": 1.88
    },
    {
      "address": "0x74b23Ecb1692363F0532069801Ce47D027417FB1",
      "pct": 1.23
    },
    {
      "address": "0x2AA9da61Eff59037eB661e2784Eb405673C19263",
      "pct": 1.22
    },
    {
      "address": "0x0a6EBEd0155EDB4b21D92AD02897A626CD90119E",
      "pct": 1.19
    },
    {
      "address": "0x6d259869Be6f63AD5EB8a27C53A97532Af803F38",
      "pct": 1.16
    },
    {
      "address": "0x492CE2CE9734CdC3488A0086b81212b3aaC40947",
      "pct": 1.14
    },
    {
      "address": "0xBd716393f9CEf81213CC49deCdDA1946C100c51d",
      "pct": 1.11
    }
  ],
  "RAXOL": [
    {
      "address": "0xe2890629EF31b32132003C02B29a50A025dEeE8a",
      "pct": 18.95
    },
    {
      "address": "0x829d1853D4ED1f80D6c223AE8828DBDBbC1E224a",
      "pct": 4.47
    },
    {
      "address": "0x5638484ba2d2F1D1D35020572B0Aa439a9869192",
      "pct": 1.07
    },
    {
      "address": "0x6fCe541eE57550CaDFA6a6E9b3450Ae35BC9179c",
      "pct": 0.74
    },
    {
      "address": "0xed5f5e5F9D3B6DC69A4C5088D80AE358Bb4f6134",
      "pct": 0.74
    },
    {
      "address": "0x55328Ff701aE1c3B9E100C2eBF82A61aB9AD5995",
      "pct": 0.71
    },
    {
      "address": "0x82608Cb7bA84322a7a0d4cC0Df8F1D2D065877ef",
      "pct": 0.68
    },
    {
      "address": "0xC0e7EA1a1ced9007f5fB45CD45908746A87Ee79B",
      "pct": 0.65
    },
    {
      "address": "0xf5948dc2b78b826EE196E54CB1b7c64cB1ca30CC",
      "pct": 0.59
    },
    {
      "address": "0x4e03cfb39c0e9aD3E8608A9749cd07FCc3E5F6F0",
      "pct": 0.55
    }
  ],
  "KARMA": [
    {
      "address": "0xe2890629EF31b32132003C02B29a50A025dEeE8a",
      "pct": 18.95
    },
    {
      "address": "0x07Cd9A8597Fc4D00a3690992A1b7151131F76758",
      "pct": 9.78
    },
    {
      "address": "0x829d1853D4ED1f80D6c223AE8828DBDBbC1E224a",
      "pct": 1.56
    },
    {
      "address": "0xa9090D67e8F9daE35A90921E08f88CD74036694c",
      "pct": 0.72
    },
    {
      "address": "0x49B6b1Fc759C1b0B4397d9Ab9fbCab0442B5F460",
      "pct": 0.7
    },
    {
      "address": "0x2C9Ee560e9D05E5df0764B9C9451b71498dE43c0",
      "pct": 0.59
    },
    {
      "address": "0xD72e00E6B984Ced3234f8B0ede7d33B04b8D63C1",
      "pct": 0.58
    },
    {
      "address": "0x578A629dF669BE6e873f142903373BA29F7e2b1F",
      "pct": 0.46
    },
    {
      "address": "0x4b4A17fBD2fD65c5Ace3e533080147DB343a893E",
      "pct": 0.41
    },
    {
      "address": "0x24E414606a7BeC29a56C3cbD3Eae5665DD0477A7",
      "pct": 0.39
    }
  ],
  "HMM": [
    {
      "address": "0x6434d19C2E6788E53AA3ec5c6fc0112b1852E554",
      "pct": 2.42
    },
    {
      "address": "0x3E93C7BBAc9CB8A0DfadbbE76B092A456652af6a",
      "pct": 1.85
    },
    {
      "address": "0xa48492aDb2eE4Fca90E2ca52af78a834A4D6b656",
      "pct": 1.85
    },
    {
      "address": "0xda4bCee76B29EFEc9697Fcf663601c2042043968",
      "pct": 1.58
    },
    {
      "address": "0x7Fac2160bAb6D465107A10A1B13f6e7EBe8B4A2c",
      "pct": 1.41
    }
  ]
};
